### ISSUE TITLE
Provide images stored locally on the server AND uploaded by the user

### ISSUE THREAD

**Issue by fplett** [mayerph/OOMWizard#1]

**Comment by mayerph** [comment]
image storage structure
https://github.com/mayerph/OOMWizard/commit/45413e1ef303812999823e4875ba2b85420d9166

**Comment by mayerph** [comment]
image upload function. Error handling still missing. 
https://github.com/mayerph/OOMWizard/commit/7bde3bf1bfe2f0f804d53dc89bd2f1dcf17579a5
