### ISSUE TITLE
Create a set of images (provided as a zip file), e.g. from one image but a list of different texts

### ISSUE THREAD

**Issue by fplett** [mayerph/OOMWizard#16]
- [x] **Create a single image with bottom/top text (1)(mandatory)**
- [x] Create a single image with multiple textboxes at chosen locations and text format. (2)
- [x] Create a set of images (provided as a zip file), e.g. from one image but a list of different texts (3)

**Comment by mayerph** [comment]
https://github.com/mayerph/OOMWizard/commit/b5c0d31080fd50dee8ca6a223456b701e3cad50b
